//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public int status { get; set; }
        public string nameInfo { get; set; }
        public int stops { get; set; }
        public int start { get; set; }
        public int end { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
